{
 "title": "TuGraph监控页面",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "磁盘",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "resources_report{instance=\"localhost:9111\",job=\"tugraph\",resouces_type=\"disk\",type=\"available\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "resources_report{instance=\"localhost:9111\",job=\"tugraph\",resouces_type=\"disk\",type=\"graph_used\"}",
     "legendFormat": "{{type}}"
    },
    { "downsampler": "mean", "expression": "$C - $A - $B", "type": "math", "upsampler": "fillna" }
   ]
  },
  {
   "title": "请求统计",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": " " } },
   "targets": [
    {
     "expr": "{instance=\"localhost:9111\",job=\"tugraph\",resouces_type=\"request\",type=~\"total|write\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "内存",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "resources_report{instance=\"localhost:9111\",job=\"tugraph\",resouces_type=\"memory\",type=\"graph_used\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "resources_report{instance=\"localhost:9111\",job=\"tugraph\",resouces_type=\"memory\",type=\"available\"}",
     "legendFormat": "{{type}}"
    },
    { "expression": "$C -$A - $B", "type": "math" }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "resources_report{instance=\"localhost:9111\",job=\"tugraph\",resouces_type=\"cpu\",type=~\"graph_used|total_used\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "磁盘IO",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "resources_report{instance=\"localhost:9111\",job=\"tugraph\",resouces_type=\"io\",type=~\"read|write\"}",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}